### ISSUE TITLE
Isn't this a React re-implementation?

### ISSUE THREAD

**Issue by hugows** [madhadron/mvc_for_the_web#1]
I came here from an HN comment. I took a glance at your code - its very nice but instead of making React unnecessary, it actually shows how much it does for you. This repo feels like the beginnings of React / Vuejs. 
(I'd love to read more about it)

**Comment by madhadron** [comment]
I've started codifying this into a library at https://github.com/madhadron/allorryll. If you've been writing frontend stuff for a while (it's been since the '90's for me), it can be hard to get what's going on.

It's not a React reimplementation. React accepts HTML as part of the program source. However, HTML is part of the problem, not part of the solution. It spreads definitions across HTML and JavaScript. It makes you spend time looking up elements and getting references to them from JavaScript. It forces something like the shadow DOM to handle updates efficiently. And using HTML elements as the anchor for views makes large, compound views such as table-trees work very differently from simple one likes buttons. React spent a lot of cleverness to get around that problem, and that was only the view part of MVC. Libraries like Redux (though they've added all kinds of great things) are crippled by this as well. Since large, compound views can't be sensibly isolated in React, their internal state bleeds into the primary model instead of encapsulating their own MVC instance inside, so now you need a much more sophisticated model layer. And Vue.js is about databinding into HTML, so if you remove the HTML, there's no reason to worry about it.
